# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eb768f93decfb9757de396ff52cabe837bb803aa772e5c513aa811956ca9d1fadd816d3268d358cd3c1dd9ec746b35c48545b03352f1de8f9791c6b418fe2c40

test:
  secret_key_base: f5c4d16e515fbad6a94c378ce0d1132a2b8ee870229a220cf26964d4bca92f87328c6946dae0ad125f9beda98675aca324ba5d0b6fe2b0d0eb01b20d268a2bbb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
